services:
  - type: web
    name: quizapp1
    env: java
    plan: free
    repo: https://github.com/aswin3112sand/quizapp1
    branch: main

    buildCommand: mvn -B clean package -DskipTests
    startCommand: java -jar target/*.jar

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: quizapp-db
          property: jdbcConnectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: quizapp-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: quizapp-db
          property: password
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: PORT
        value: 8080

databases:
  - name: quizapp-db
    databaseName: quizapp
    plan: free
